# Autogenerated by nbdev

d = { 'settings': { 'branch': 'nbdev',
                'doc_baseurl': '/pypaths',
                'doc_host': 'https://mrfruitcakeforever.github.io',
                'git_url': 'https://github.com/mrfruitcakeforever/pypaths',
                'lib_path': 'pypaths'},
  'syms': {'pypaths.core': {'pypaths.core.foo': ('core.html#foo', 'pypaths/core.py')}}}
